steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/${_PROJECT_ID}/containers/${_IMAGE}:${COMMIT_SHA}', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast2-docker.pkg.dev/${_PROJECT_ID}/containers/${_IMAGE}:${COMMIT_SHA}']
- id: 'create-attestation'
  name: 'gcr.io/${_PROJECT_ID}/binauthz-attestation:latest'
  args: 
    - '--artifact-url'
    - 'gcr.io/${_PROJECT_ID}/helloworld:latest'
    - '--attestor'
    - 'projects/${_PROJECT_ID}/attestors/${_ATTESTOR_NAME}'
    - '--keyversion'
    - 'projects/${_PROJECT_ID}/locations/global/keyRings/${_KMS_KEYRING_NAME}/cryptoKeys/${_KMS_KEY_NAME}/cryptoKeyVersions/1'  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['deploy', 'releases', 'create', 'test-release-${SHORT_SHA}', '--skaffold-file', './deploy/skaffold.yaml','--project', 'next22-demo-1', '--region', 'asia-southeast2', '--delivery-pipeline', 'demo-clouddeploy', '--images=my-app-image=asia-southeast2-docker.pkg.dev/${_PROJECT_ID}/containers/${_IMAGE}:${COMMIT_SHA}']
images: ['asia-southeast2-docker.pkg.dev/${_PROJECT_ID}/containers/${_IMAGE}:${COMMIT_SHA}']
options:
  requestedVerifyOption: VERIFIED