apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: frontend
build:
  artifacts:
    - image: frontend-v2
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - frontend.yaml
