apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: demo-clouddeploy
description: main application pipeline
serialPipeline:
 stages:
 - targetId: devtarget
   profiles: 
   - dev
 - targetId: prodtarget
   profiles:
   - prod
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: devtarget
description: development namespace
gke:
 cluster: projects/next22-demo-1/locations/asia-southeast2/clusters/autopilot-cluster-1
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: prodtarget
description: production namespace
gke:
 cluster: projects/next22-demo-1/locations/asia-southeast2/clusters/autopilot-cluster-1
requireApproval: true